language: python

python:
    - "2.7"

services:
    - redis-server

install:
    - sudo apt-get install python-pip
    - pip install -r requirements.txt

before_script:
    - psql -c 'create database twobuntu;' -U postgres

script:
    - cp twobuntu/local_settings.py.default twobuntu/local_settings.py
    - |
      echo "DATABASES = {
          'default': {
              'ENGINE': 'django.db.backends.postgresql_psycopg2',
              'NAME': 'twobuntu',
              'USER': 'postgres',
          },
      }
      SECRET_KEY = '1234567890abcdef'" >> twobuntu/local_settings.py
    - ./manage.py syncdb --noinput
    - ./manage.py migrate --noinput
    - ./manage.py test --noinput
